openapi: 3.0.0

info:
  title: Example Express
  description: Criado para API de Exemplo
  version: 0.0.1

servers:
  - url: http://localhost:3000
    description: Desenvolvimento

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

tags:
  - name: Contato
    description: Contatos namespace
  - name: System
    description: System namespace

paths:
  /v1/system/healthcheck:
    get:
      tags:
        - System
      summary: Retorna o status da API.
      responses:
        200: # status code
          description: Retorna o status da API.
          content:
            application/json:
              schema:
                type: string
                example: "OK"
        500: # status code
          $ref: "#/components/responses/internal"

  /v1/system/metrics:
    get:
      tags:
        - System
      summary: Retorna metricas da API.
      responses:
        200: # status code
          description: Retorna metricas da API.
          content:
            application/json:
              schema:
                type: string
        500: # status code
          $ref: "#/components/responses/internal"

  /v1/contact/amqp:
    post:
      tags:
        - Contato
      summary: Criação de contatos por fila AMQP.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contact"
      responses:
        200: # status code
          description: Cadastro de contatos.
          content:
            application/json:
              schema:
                type: string
                example: "Criado com sucesso ID 1"
        400: # status code
          $ref: "#/components/responses/badRequest"
        500: # status code
          $ref: "#/components/responses/internal"
          
  /v1/contact:
    get:
      tags:
        - Contato
      summary: Retorna a lista de contatos.
      parameters:
        - in: query
          name: nome
          description: Nome do contato
          schema:
            type: string
            example: "Ismael Alves"
        - in: query
          name: telefone
          description: Telefone do contato
          schema:
            type: string
            example: "8598546123145"
      responses:
        200: # status code
          $ref: "#/components/responses/contact"

    post:
      tags:
        - Contato
      summary: Criação de contatos.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contact"
      responses:
        200: # status code
          description: Cadastro de contatos.
          content:
            application/json:
              schema:
                type: string
                example: "Criado com sucesso ID 1"
        400: # status code
          $ref: "#/components/responses/badRequest"
        500: # status code
          $ref: "#/components/responses/internal"

  /v1/contact/{id}:
    get:
      tags:
        - Contato
      summary: Retorna um contato por ID.
      parameters:
        - in: path
          required: true
          name: id
          description: ID do contato
          schema:
            type: string
            example: "1"
      responses:
        200: # status code
          description: lista de contato.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 1
                  name:
                    type: string
                    example: "Carlos"
                  phone:
                    type: string
                    example: "2835086501612"
                  createdAt:
                    type: string
                    example: "2021-03-31 22:34:36.476"
                  updatedAt:
                    type: string
                    example: "2021-03-31 22:34:36.476"
        400: # status code
          $ref: "#/components/responses/badRequest"
        500: # status code
          $ref: "#/components/responses/internal"

    put:
      tags:
        - Contato
      summary: Atualiza um contato.
      parameters:
        - in: path
          required: true
          name: id
          description: ID do contato
          schema:
            type: string
            example: "1"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contact"
      responses:
        200: # status code
          description: Retorna status.
          content:
            application/json:
              schema:
                type: string
                example: "ID 1 Atualizado com sucesso"
        400: # status code
          $ref: "#/components/responses/badRequest"
        500: # status code
          $ref: "#/components/responses/internal"

    delete:
      tags:
        - Contato
      summary: Deleta um contato.
      parameters:
        - in: path
          required: true
          name: id
          description: ID do contato
          schema:
            type: string
            example: "1"
      responses:
        200: # status code
          description: Retorna a lista de contatos.
          content:
            application/json:
              schema:
                type: string
                example: "Deletado com sucesso ID 1"
        400: # status code
          $ref: "#/components/responses/badRequest"
        500: # status code
          $ref: "#/components/responses/internal"

components:
  responses:
    badRequest:
      description: Falha na request.
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string

    notFound:
      description: valor não encontrado.
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string

    internal:
      description: erro interno.
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string

    contact:
      description: lista de contatos.
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: number
                  example: 1
                name:
                  type: string
                  example: "Ismael Alves"
                phone:
                  type: string
                  example: "2835086501612"
                createdAt:
                  type: string
                  example: "2021-03-31 22:34:36.476"
                updatedAt:
                  type: string
                  example: "2021-03-31 22:34:36.476"

  schemas:
    contact:
      type: object
      required:
        - nome
        - phone
      properties:
        name:
          type: string
          example: "Ismael Alves"
        phone:
          type: string
          example: "8598546123145"
