{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: {{ template "service.fullname" . }}-ingress
  {{- if or .Values.namespace .Release.Namespace }}
  namespace: {{ or .Values.namespace .Release.Namespace }}
  {{- end}}
  annotations:
    {{ include "service.annotations" . }}
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewrite }}
    # nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslRedirect }}
    # nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.forceSslRedirect }}
    # nginx.ingress.kubernetes.io/ssl-passthrough: {{ .Values.ingress.sslPassthrough }}
    # nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.proxySendTimeout }}
    # nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.proxyRendTimeout }}

spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  {{ template "service.fullname" . }}
            port: 
              number: {{ .Values.env.SERVER_PORT }}
{{- end }}